current_node_id: node3
current_port: 18083
current_node_addr: localhost:18083
all_members:
  - node_id: node1
    node_uri: localhost:18080
  - node_id: node2
    node_uri: localhost:18081
  - node_id: node3
    node_uri: localhost:18082