// Code generated by MockGen. DO NOT EDIT.
// Source: common/config.go
//
// Generated by this command:
//
//	mockgen -source=common/config.go -destination=./common/config_mock.go -package common
//

// Package common is a generated GoMock package.
package common

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockConfigManager is a mock of ConfigManager interface.
type MockConfigManager struct {
	ctrl     *gomock.Controller
	recorder *MockConfigManagerMockRecorder
	isgomock struct{}
}

// MockConfigManagerMockRecorder is the mock recorder for MockConfigManager.
type MockConfigManagerMockRecorder struct {
	mock *MockConfigManager
}

// NewMockConfigManager creates a new mock instance.
func NewMockConfigManager(ctrl *gomock.Controller) *MockConfigManager {
	mock := &MockConfigManager{ctrl: ctrl}
	mock.recorder = &MockConfigManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigManager) EXPECT() *MockConfigManagerMockRecorder {
	return m.recorder
}

// GetClusterSize mocks base method.
func (m *MockConfigManager) GetClusterSize() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClusterSize")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetClusterSize indicates an expected call of GetClusterSize.
func (mr *MockConfigManagerMockRecorder) GetClusterSize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClusterSize", reflect.TypeOf((*MockConfigManager)(nil).GetClusterSize))
}

// GetDataDir mocks base method.
func (m *MockConfigManager) GetDataDir() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDataDir")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetDataDir indicates an expected call of GetDataDir.
func (mr *MockConfigManagerMockRecorder) GetDataDir() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDataDir", reflect.TypeOf((*MockConfigManager)(nil).GetDataDir))
}

// GetElectionTimeout mocks base method.
func (m *MockConfigManager) GetElectionTimeout() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetElectionTimeout")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// GetElectionTimeout indicates an expected call of GetElectionTimeout.
func (mr *MockConfigManagerMockRecorder) GetElectionTimeout() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetElectionTimeout", reflect.TypeOf((*MockConfigManager)(nil).GetElectionTimeout))
}

// GetGracefulShutdownTimeout mocks base method.
func (m *MockConfigManager) GetGracefulShutdownTimeout() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGracefulShutdownTimeout")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// GetGracefulShutdownTimeout indicates an expected call of GetGracefulShutdownTimeout.
func (mr *MockConfigManagerMockRecorder) GetGracefulShutdownTimeout() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGracefulShutdownTimeout", reflect.TypeOf((*MockConfigManager)(nil).GetGracefulShutdownTimeout))
}

// GetLeaderHeartbeatPeriod mocks base method.
func (m *MockConfigManager) GetLeaderHeartbeatPeriod() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLeaderHeartbeatPeriod")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// GetLeaderHeartbeatPeriod indicates an expected call of GetLeaderHeartbeatPeriod.
func (mr *MockConfigManagerMockRecorder) GetLeaderHeartbeatPeriod() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLeaderHeartbeatPeriod", reflect.TypeOf((*MockConfigManager)(nil).GetLeaderHeartbeatPeriod))
}

// GetMembership mocks base method.
func (m *MockConfigManager) GetMembership() Membership {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMembership")
	ret0, _ := ret[0].(Membership)
	return ret0
}

// GetMembership indicates an expected call of GetMembership.
func (mr *MockConfigManagerMockRecorder) GetMembership() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMembership", reflect.TypeOf((*MockConfigManager)(nil).GetMembership))
}

// GetRPCDeadlineMargin mocks base method.
func (m *MockConfigManager) GetRPCDeadlineMargin() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRPCDeadlineMargin")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// GetRPCDeadlineMargin indicates an expected call of GetRPCDeadlineMargin.
func (mr *MockConfigManagerMockRecorder) GetRPCDeadlineMargin() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRPCDeadlineMargin", reflect.TypeOf((*MockConfigManager)(nil).GetRPCDeadlineMargin))
}

// GetRPCRequestTimeout mocks base method.
func (m *MockConfigManager) GetRPCRequestTimeout() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRPCRequestTimeout")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// GetRPCRequestTimeout indicates an expected call of GetRPCRequestTimeout.
func (mr *MockConfigManagerMockRecorder) GetRPCRequestTimeout() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRPCRequestTimeout", reflect.TypeOf((*MockConfigManager)(nil).GetRPCRequestTimeout))
}

// GetRaftNodeRequestBufferSize mocks base method.
func (m *MockConfigManager) GetRaftNodeRequestBufferSize() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRaftNodeRequestBufferSize")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetRaftNodeRequestBufferSize indicates an expected call of GetRaftNodeRequestBufferSize.
func (mr *MockConfigManagerMockRecorder) GetRaftNodeRequestBufferSize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRaftNodeRequestBufferSize", reflect.TypeOf((*MockConfigManager)(nil).GetRaftNodeRequestBufferSize))
}

// GetgRPCServiceConf mocks base method.
func (m *MockConfigManager) GetgRPCServiceConf() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetgRPCServiceConf")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetgRPCServiceConf indicates an expected call of GetgRPCServiceConf.
func (mr *MockConfigManagerMockRecorder) GetgRPCServiceConf() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetgRPCServiceConf", reflect.TypeOf((*MockConfigManager)(nil).GetgRPCServiceConf))
}

// String mocks base method.
func (m *MockConfigManager) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockConfigManagerMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockConfigManager)(nil).String))
}

// Validate mocks base method.
func (m *MockConfigManager) Validate() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate")
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockConfigManagerMockRecorder) Validate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockConfigManager)(nil).Validate))
}
