// Code generated by MockGen. DO NOT EDIT.
// Source: mkraft/node/consensus.go
//
// Generated by this command:
//
//	mockgen -source=mkraft/node/consensus.go -destination=./mkraft/node/consensus_mock.go -package node
//

// Package node is a generated GoMock package.
package node
