current_node_id: node1
current_port: 18080
current_node_addr: localhost:18080
all_members:
  - node_id: node1
    node_uri: localhost:18080
  - node_id: node2
    node_uri: localhost:18081
  - node_id: node3
    node_uri: localhost:18082