# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Test and Coverage

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.24"
      - run: make build
      - run: go test -v ./... -coverprofile=coverage.out
      - name: Upload coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: coverage.out

  coverage-report:
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v4
  
      # Download the coverage artifact from the current build
      - uses: actions/download-artifact@v4
        with:
          name: code-coverage
          path: .
    
      # Generate the coverage report
      - name: Generate coverage report
        if: github.event_name == 'pull_request'
        uses: fgrosse/go-coverage-report@v1.2.0
        with:
          coverage-file-name: coverage.out
          report-only: ${{ github.event_name != 'push' }}